# mybatis
mybatis:
  type-aliases-package: com.wangde007.entity

# server
server:
  port: 9180
  display-name: wangde007
  tomcat:
    accesslog:
      enabled: true
    basedir: target/tomcateLog
  session:
    timeout: 3600



# LOG4J
logging:
  path: ./target/log4j

#datasource
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
  thymeleaf:
    mode: HTML5
    cache: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    timeout: 0
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
  session:
    store-type: REDIS







