# mybatis
mybatis:
  type-aliases-package: com.wangde007.entity

# server
server:
  port: 9189
  display-name: wangde007
  tomcat:
    accesslog:
      enabled: true
    basedir: target/tomcateLog

# LOG4J
#logging:
#  path: ./target/log4j

#datasource
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
  thymeleaf:
    mode: HTML5
    cache: true






